# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: notahtah <notahtah@student.codam.nl>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/10/18 13:20:51 by notahtah          #+#    #+#              #
#    Updated: 2024/01/15 04:23:48 by notahtah         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=		libft.a

CC			=		cc

CFLAGS		=		-Wall -Wextra -Werror

SRCS		=		ft_atoi.c				\
					ft_bzero.c				\
					ft_calloc.c				\
					ft_isalnum.c			\
					ft_isascii.c			\
					ft_isalpha.c			\
					ft_isdigit.c			\
					ft_isprint.c			\
					ft_itoa.c				\
					ft_memchr.c				\
					ft_memcmp.c				\
					ft_memcpy.c				\
					ft_memmove.c			\
					ft_memset.c				\
					ft_putchar_fd.c			\
					ft_putendl_fd.c			\
					ft_putnbr_fd.c			\
					ft_putstr_fd.c			\
					ft_split.c				\
					ft_strdup.c				\
					ft_strchr.c				\
					ft_striteri.c			\
					ft_strjoin.c			\
					ft_strlcat.c			\
					ft_strlcpy.c			\
					ft_strlen.c				\
					ft_strmapi.c			\
					ft_strncmp.c			\
					ft_strnstr.c			\
					ft_strrchr.c			\
					ft_strtrim.c			\
					ft_substr.c				\
					ft_tolower.c			\
					ft_toupper.c			\
					ft_print_chars.c		\
					ft_print_hex.c			\
					ft_print_integer.c		\
					ft_print_pointer.c 		\
					ft_printf.c				\

OBJS		=		$(SRCS:%.c=%.o)

$(NAME):	
			@$(CC) $(CFLAGS) -c $(SRCS)
			@ar -rc $(NAME) $(OBJS)

all:		$(NAME)

clean:
			@rm -f $(OBJS)

fclean: 	clean
			@rm -f $(NAME)

re:			fclean all

.PHONY:		all clean fclean re